# Generated by Django 6.0.1 on 2026-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_venta_caja_alter_venta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
