# Generated by Django 6.0.1 on 2026-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_detalleventa_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprobante',
            field=models.CharField(blank=True, help_text='Nro. de comprobante o referencia', max_length=100, null=True),
        ),
    ]
