# Generated by Django 6.0.1 on 2026-01-26 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='miembros.disciplina')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='miembros.miembro')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('miembro', 'disciplina', 'fecha_vencimiento')},
            },
        ),
    ]
