# Generated by Django 6.0.1 on 2026-01-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_membresia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membresia',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_vencimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
