# Generated by Django 6.0.1 on 2026-01-26 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_alter_membresia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+595981123456' o '0981123456'.", regex='^\\+?595\\d{9}$|^09\\d{8}$')]),
        ),
    ]
