# Generated by Django 6.0.1 on 2026-01-28 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_alter_miembro_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('INACTIVO', 'Inactivo')], default='INACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '09xxxxxxxx' (ej. 0984123456).", regex='^09\\d{8}$')]),
        ),
    ]
