# Generated by Django 6.0.1 on 2026-01-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0006_alter_miembro_estado_alter_miembro_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='precio',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='precio_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='precio_quincenal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='precio_semanal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='membresia',
            name='tipo',
            field=models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='MENSUAL', max_length=15),
        ),
    ]
