# Generated by Django 6.0.1 on 2026-01-30 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0007_remove_disciplina_precio_disciplina_precio_diario_and_more'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='transaccion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresia_asociada', to='tesoreria.transaccion'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
