# Generated by Django 6.0.1 on 2026-03-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0008_membresia_transaccion_alter_membresia_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
