# Generated by Django 6.0.1 on 2026-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0009_membresia_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='comprobante',
            field=models.CharField(blank=True, help_text='Nro. de comprobante o referencia', max_length=100, null=True),
        ),
    ]
