# Generated by Django 6.0.1 on 2026-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0010_membresia_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20),
        ),
    ]
