# Generated by Django 6.0.1 on 2026-01-29 02:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros', '0007_remove_disciplina_precio_disciplina_precio_diario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final_teorico', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado al cerrar', max_digits=10, null=True)),
                ('monto_final_real', models.DecimalField(blank=True, decimal_places=2, help_text='Ingresado por el cajero al cerrar', max_digits=10, null=True)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('CONTABILIZADA', 'Contabilizada')], default='ABIERTA', max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEMBRESIA', 'Membresía'), ('PRODUCTO', 'Producto'), ('INGRESO_VARIO', 'Ingreso Vario'), ('EGRESO_VARIO', 'Egreso Vario')], max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='tesoreria.caja')),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='miembros.miembro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.CharField(blank=True, help_text='Nro. de comprobante o referencia', max_length=100, null=True)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tesoreria.transaccion')),
            ],
            options={
                'verbose_name': 'Detalle de Transacción',
                'verbose_name_plural': 'Detalles de Transacciones',
            },
        ),
    ]
