# Generated by Django 6.0.1 on 2026-02-27 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('tesoreria', '0002_alter_transaccion_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTransaccionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario de Venta')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sub Total')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_productos', to='tesoreria.transaccion')),
            ],
            options={
                'verbose_name': 'Detalle de Transacción (Producto)',
                'verbose_name_plural': 'Detalles de Transacciones (Productos)',
                'unique_together': {('transaccion', 'producto')},
            },
        ),
    ]
