# Generated by Django 6.0.1 on 2026-03-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0003_detalletransaccionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('MEMBRESIA', 'Membresía'), ('INGRESO_VARIO', 'Ingreso Vario'), ('EGRESO_VARIO', 'Egreso Vario')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DetalleTransaccionProducto',
        ),
    ]
