# Generated by Django 6.0.1 on 2026-03-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_alter_transaccion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('MEMBRESIA', 'Membresía'), ('INGRESO_VARIO', 'Ingreso Vario'), ('EGRESO_VARIO', 'Egreso Vario'), ('VENTA_PRODUCTO', 'Venta de Producto')], max_length=20),
        ),
    ]
