# Generated by Django 6.0.1 on 2026-03-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='CONFIRMADA', max_length=15),
        ),
    ]
