# Generated by Django 6.0.1 on 2026-03-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_venta_detalleventa'),
        ('tesoreria', '0006_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_venta', to='inventario.venta'),
        ),
    ]
