# Generated by Django 6.0.1 on 2026-03-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0008_membresia_transaccion_alter_membresia_fecha_inicio_and_more'),
        ('tesoreria', '0007_transaccion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_membresia', to='miembros.membresia'),
        ),
    ]
