# Generated by Django 6.0.1 on 2026-03-31 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0008_transaccion_membresia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('es_tesoreria', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TESORERIA', 'Tesorería'), ('BANCARIA', 'Bancaria'), ('INTERNA', 'Interna')], max_length=15)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('es_principal', models.BooleanField(default=False)),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='tesoreria.banco')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito (Entrada)'), ('DEBITO', 'Débito (Salida)')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('origen', models.CharField(choices=[('TRANSACCION', 'Transacción'), ('CIERRE_CAJA', 'Cierre de Caja'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDIENTE', 'Pendiente'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tesoreria.cuenta')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta',
                'verbose_name_plural': 'Movimientos de Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='tesoreria.cuenta')),
                ('movimiento_destino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_de_entrada', to='tesoreria.movimientocuenta')),
                ('movimiento_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencia_de_salida', to='tesoreria.movimientocuenta')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='tesoreria.cuenta')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
            },
        ),
        migrations.CreateModel(
            name='CuentaMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='tesoreria.cuenta')),
            ],
            options={
                'verbose_name': 'Saldo por Método de Pago',
                'verbose_name_plural': 'Saldos por Método de Pago',
                'unique_together': {('cuenta', 'metodo_pago')},
            },
        ),
    ]
