# Generated by Django 6.0.1 on 2026-03-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0009_banco_cuenta_movimientocuenta_transferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='cuenta',
            field=models.ForeignKey(blank=True, help_text='Cuenta interna asignada a esta caja', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='tesoreria.cuenta'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deprecado: Diferencia entre real y cuenta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_final_teorico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deprecado: Se calcula desde la cuenta', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocuenta',
            name='origen',
            field=models.CharField(choices=[('TRANSACCION', 'Transacción'), ('CIERRE_CAJA', 'Cierre de Caja'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste'), ('APERTURA_CAJA', 'Apertura de Caja')], max_length=20),
        ),
    ]
