# Generated by Django 6.0.1 on 2026-04-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0010_caja_cuenta_alter_caja_diferencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], max_length=20, unique=True, verbose_name='Método de Pago')),
                ('cuenta_destino', models.ForeignKey(help_text='Cuenta donde se depositarán los fondos al contabilizar la caja.', on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_destino', to='tesoreria.cuenta', verbose_name='Cuenta Destino')),
            ],
            options={
                'verbose_name': 'Configuración de Destino de Pago',
                'verbose_name_plural': 'Configuraciones de Destinos de Pago',
            },
        ),
    ]
