# Generated by Django 6.0.1 on 2026-04-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0011_metodopagoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='referencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
